// <auto-generated />
namespace ShoeStore.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Cat_SubCat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cat_SubCat));
        
        string IMigrationMetadata.Id
        {
            get { return "202004200812009_Cat_SubCat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
