// <auto-generated />
namespace ShoeStore.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ProductId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductId));
        
        string IMigrationMetadata.Id
        {
            get { return "202004200834538_ProductId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
